/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.net.URL;
import javax.swing.ImageIcon;

/**
 *
 * @author iband
 */
public class FrMenu extends javax.swing.JFrame {

  /**
   * Creates new form FrMenu
   */
  public FrMenu() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    btnCadastroGrupos = new javax.swing.JButton();
    btnSortear = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Sorteio de Grupos");
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowOpened(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
      }
    });
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jPanel1.setBackground(new java.awt.Color(0, 0, 0));
    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    btnCadastroGrupos.setBackground(new java.awt.Color(255, 255, 255));
    btnCadastroGrupos.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
    btnCadastroGrupos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pessoa_grande.png"))); // NOI18N
    btnCadastroGrupos.setText("Cadastro de Grupos");
    btnCadastroGrupos.setFocusPainted(false);
    btnCadastroGrupos.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnCadastroGruposMouseClicked(evt);
      }
    });
    jPanel1.add(btnCadastroGrupos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

    btnSortear.setBackground(new java.awt.Color(255, 255, 255));
    btnSortear.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
    btnSortear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/serra_grande_nova.png"))); // NOI18N
    btnSortear.setText("Sortear");
    btnSortear.setFocusPainted(false);
    btnSortear.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        btnSortearMouseClicked(evt);
      }
    });
    jPanel1.add(btnSortear, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, -1));

    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/jigsaw_cortado.png"))); // NOI18N
    jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, -1, -1));

    getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 742, -1));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnCadastroGruposMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastroGruposMouseClicked
    FrManterGrupos tela = new FrManterGrupos(this, rootPaneCheckingEnabled);
    
    tela.setVisible(true);
  }//GEN-LAST:event_btnCadastroGruposMouseClicked

  private void btnSortearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSortearMouseClicked
    FrSorteio tela = new FrSorteio(this, rootPaneCheckingEnabled);
    
    tela.setVisible(true);
  }//GEN-LAST:event_btnSortearMouseClicked

  private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    URL caminhoImagem = getClass().getResource("/images/serra_icone.png");

    ImageIcon icon = new ImageIcon(caminhoImagem);

    // Define o ícone da janela
    this.setIconImage(icon.getImage());
  }//GEN-LAST:event_formWindowOpened

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(FrMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new FrMenu().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastroGrupos;
  private javax.swing.JButton btnSortear;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
